### ISSUE TITLE
Ajouter une vue pour le profile d'une entreprise 

### ISSUE THREAD

**Issue by abbesdjilali** [ArtasArio/ACME#10]
Lorsque le client clique sur le nom de son entreprise dans la page https://centuri.dev/order/read/1-auwhrtvjqr9mb6ty
une page 404 s'affiche https://centuri.dev/provider/read/okuneva-ullrich-and-adams-4jrjwvxc

il faut ajouter une page profile entreprise ou bien désactivé le lien dans la page https://centuri.dev/order/read/1-auwhrtvjqr9mb6ty

**Comment by ArtasArio** [comment]
J'ai retiré le lien, les données des clients sont normalement déjà connu au responsable du client en question.
