### ISSUE TITLE
Attaché un user à un client

### ISSUE THREAD

**Issue by abbesdjilali** [ArtasArio/ACME#11]
Lorsque un nouveau utilisateur s’enregistre  il n'est pas attaché à une entreprise (client) et il ne peux pas voir sans panier (redirection vers la page https://centuri.dev/dashboard sans message d'information 
Il faut soit lorsque l'admin de ACME ajoute un client on donne la possibilité au client d'ajouter ses manager (users) et supprimé l'accès aux public à la page https://centuri.dev/register

**Comment by ArtasArio** [comment]
Il faut soit lorsque l'admin de ACME ajoute un client on donne la possibilité au client d'ajouter ses manager (users) et supprimé l'accès aux public à la page https://centuri.dev/register
Un manager (gérant un client) pourrait faire n'importe quoi avec ses droits et ajouter n'importe qui

J'ai mis un message d'erreurlors que l'utilisateur n'a pas de client associé (cad n'est pas associé à une entreprise est donc n'es pas un responsable)
