### ISSUE TITLE
order sans client_id et le lien https://centuri.dev/cart/checkout crée automatiquement une commande même si le panier est vide 

### ISSUE THREAD

**Issue by abbesdjilali** [ArtasArio/ACME#13]
lorsque un user n'est pas attaché à une entreprise (client) il peut voir les produit dans la page https://centuri.dev/shop/browse et ajouter des produits dans son panier 
l'accès vers la page https://centuri.dev/cart/index n'est pas accessible car il y a une redirection vers https://centuri.dev/dashboard et c'est très bien sauf que si dans l'url  https://centuri.dev/cart/checkout ça crée une commande meme si le panier est vide

**Comment by ArtasArio** [comment]
/cart/checkout bloqué si pas de produits dans le panier
l'ajout de produit dans le panier bloqué si pas de client_id
/cart/index redirige maintenant vers dashboard avec un message d'erreur lorsque l'utilisateur n'est pas attaché à un client
