### ISSUE TITLE
Doublons table fournisseur et catégorie

### ISSUE THREAD

**Issue by abbesdjilali** [ArtasArio/ACME#5]
lors de l'ajout d'un nouveau fournisseur ou une nouvelle catégorie je propose d'ajouter une vérification sur le nom de fournisseur pour voir si il existe ou pas 
path : https://centuri.dev/provider/add
https://centuri.dev/category/add

**Comment by ArtasArio** [comment]
corrigé + ajouté vérifications des champs de saisie
